Fix gui error on start with wxPython 4.0.1
IconFromLocation was removed, Icon should be used instead.
Original error:
  File "./maketarget-gui.py", line 126, in init_frame
    self.frame.SetIcon(wx.IconFromLocation(loc))
AttributeError: module 'wx' has no attribute 'IconFromLocation'